#FROM python:3.10.12-alpine
#FROM ubuntu:22.04
FROM localhost:5000/monitorzkh:latest
#FROM mcr.microsoft.com/mssql/server:2022-CU14-ubuntu-22.04
#RUN pip install extra_streamlit_components
#RUN pip install psycopg2-binary
WORKDIR /var/www/html/monitorZKH
RUN  rm -rf unwanted-files
COPY . /var/www/html/monitorZKH

RUN pip install -r requirements.txt

EXPOSE 8503

HEALTHCHECK CMD curl -f http://localhost:8503/_stcore/health || exit 1

ENTRYPOINT ["streamlit", "run", "Монитор_ЖКХ.py", "--server.port=8503", "--server.address=0.0.0.0"]

ENV  PYTHONPATH="/var/www/html/monitorZKH:/var/www/html/monitorZKH/utils:/var/www/html/monitorZKH/widgets:/var/www/html/monitorZKH/utils/pages"

# Clean up
RUN apt autoremove -y && apt clean -y