server = "192.168.10.190"
database = "FIAS"
username = "SA"
password = "Neodog2020"

pg_server = "192.168.10.21"
pg_database = "mzkh"
pg_username = "postgres"
pg_password = "Neodog2020"

[passwords]
# Follow the rule: username = "password"
adm = "adm"
user = "user"